In [117]:
import pandas as pd

dataset = pd.read_csv('insurance_pre.csv')
dataset = pd.get_dummies(dataset, dtype= int)
dataset

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes
0,19,27.900,0,16884.92400,1,0,0,1
1,18,33.770,1,1725.55230,0,1,1,0
2,28,33.000,3,4449.46200,0,1,1,0
3,33,22.705,0,21984.47061,0,1,1,0
4,32,28.880,0,3866.85520,0,1,1,0
...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,0,1,1,0
1334,18,31.920,0,2205.98080,1,0,1,0
1335,18,36.850,0,1629.83350,1,0,1,0
1336,21,25.800,0,2007.94500,1,0,1,0
1337,61,29.070,0,29141.36030,1,0,0,1

In [118]:
ind_var = dataset.drop("charges", axis=1)
dep_var = dataset["charges"]
ind_var

      age     bmi  children  sex_female  sex_male  smoker_no  smoker_yes
0      19  27.900         0           1         0          0           1
1      18  33.770         1           0         1          1           0
2      28  33.000         3           0         1          1           0
3      33  22.705         0           0         1          1           0
4      32  28.880         0           0         1          1           0
...   ...     ...       ...         ...       ...        ...         ...
1333   50  30.970         3           0         1          1           0
1334   18  31.920         0           1         0          1           0
1335   18  36.850         0           1         0          1           0
1336   21  25.800         0           1         0          1           0
1337   61  29.070         0           1         0          0           1

[1338 rows x 7 columns]

In [119]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(ind_var, dep_var, test_size = 0.3, random_state= 42)

In [120]:
from sklearn.preprocessing import StandardScaler

# Standard Scaling for SVM
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [121]:
def modelScore(model, x_train, x_test, y_train, y_test):

    from sklearn.metrics import r2_score

    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    r_score = r2_score(y_test , y_pred)
    return r_score

In [122]:
def decisionTreeModel(x_train, x_test, y_train, y_test):
    from sklearn.tree import DecisionTreeRegressor

    dtRegressor = DecisionTreeRegressor(
        criterion="absolute_error", 
        splitter = "best", 
        max_depth= 5, 
        random_state=42
        )
    
    model_score = modelScore(dtRegressor, x_train, x_test, y_train, y_test)
    return model_score

In [123]:
def randomForestModel(x_train, x_test, y_train, y_test):

    from sklearn.ensemble import RandomForestRegressor
    random_forest_model = RandomForestRegressor(
        criterion = 'squared_error',
        n_estimators= 100,
        max_depth = 10,
        max_features = 'sqrt',
        random_state = 0
    )
    rf_model_score = modelScore(random_forest_model, x_train, x_test, y_train, y_test)
    return rf_model_score

In [124]:
def linearModel(x_train, x_test, y_train, y_test):
    from sklearn.linear_model import LinearRegression

    linear_model = LinearRegression()
    linear_score = modelScore(linear_model, x_train, x_test, y_train, y_test)
    return linear_score

In [125]:
def svmModel(x_train, x_test, y_train, y_test):
    from sklearn.svm import SVR

    svr_model = SVR(kernel= "linear", C=1000, gamma= 3)
    svr_score = modelScore(svr_model, X_train, X_test, y_train, y_test)
    return svr_score

In [126]:
linear_score = linearModel(X_train, X_test, y_train, y_test)
svm_score = svmModel(X_train, X_test, y_train, y_test)
decision_tree_score = decisionTreeModel(X_train, X_test, y_train, y_test)
random_forest_score = randomForestModel(X_train, X_test, y_train, y_test)

print(linear_score, '\n', svm_score, '\n', decision_tree_score, '\n', random_forest_score)

0.7680881643600721
 0.7065596185868294
 0.8628846625378732
 0.8631500601811162

In [127]:
def gradientBoostingModel(X_train, X_test, y_train, y_test):

    from sklearn.ensemble import GradientBoostingRegressor

    booster = GradientBoostingRegressor()
    gradient_score = modelScore(booster, X_train, X_test, y_train, y_test)
    return gradient_score

g_score = gradientBoostingModel(X_train, X_test, y_train, y_test)
print(g_score)

0.8650017159432917

In [134]:
def adaBoostingModel(X_train, X_test, y_train, y_test):

    from sklearn.ensemble import AdaBoostRegressor

    ada_boost = AdaBoostRegressor(
        n_estimators=200,
        learning_rate=0.1,
        random_state=42
    )
    ada_score = modelScore(ada_boost, X_train, X_test, y_train, y_test)
    return ada_score

g_score = adaBoostingModel(X_train, X_test, y_train, y_test)
print(g_score)

0.8183134849589604

In [137]:
def xgBoostingModel(X_train, X_test, y_train, y_test):

    from xgboost import XGBRegressor

    xg_boost = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=4,
    random_state=42
)

    xg_score = modelScore(xg_boost, X_train, X_test, y_train, y_test)
    return xg_score

g_score = xgBoostingModel(X_train, X_test, y_train, y_test)
print(g_score)

0.8607686799683287